language: node_js
node_js:
  - "12.5.0"

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - yarn global add @angular/cli

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run test:ci
  - yarn run webdriver-update
  - yarn run webdriver-start
  - yarn run se2e
  - yarn run ci-e2e
  - yarn run build:elements

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./elements/
  on: